### PR TITLE
Feat/support for many_to_many relationship

### PR DESCRIPTION
**Pull request by prakha**
## Issue

- resolve:

### 🤖 Generated by PR Agent at aa9db584831d2cff5311e2499ea9bf0c65f8adf9

- Added support for detecting and processing many-to-many relationships.
- Implemented utilities for creating implicit join tables and relationships.
- Enhanced schema parsing to handle many-to-many relations effectively.
- Added comprehensive test cases for many-to-many relationship handling.

## Detailed Changes

<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Tests</strong></td><td><table>
<tr>
  <td>
    <details>
      <summary><strong>index.test.ts</strong><dd><code>Added test case for many-to-many relationships</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

frontend/packages/db-structure/src/parser/prisma/index.test.ts

<li>Added test case for implicit many-to-many relationships.<br> <li> Validated schema parsing for many-to-many relationships.<br> <li> Ensured expected database structure matches parsed output.

</details>

  </td>
  <td><a href="https://github.com/liam-hq/liam/pull/1255/files#diff-994ebc8ffb1813364f3eec0fb07d7d81a7ce221866d6eb5cd68df4acee202730">+121/-0</a>&nbsp; </td>

</tr>
</table></td></tr><tr><td><strong>Enhancement</strong></td><td><table>
<tr>
  <td>
    <details>
      <summary><strong>parser.ts</strong><dd><code>Enhanced schema parser for many-to-many relationships</code>&nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

frontend/packages/db-structure/src/parser/prisma/parser.ts

<li>Added logic to detect and store many-to-many relationships.<br> <li> Implemented utilities for creating join tables and relationships.<br> <li> Enhanced schema parsing to process many-to-many relations.<br> <li> Added helper functions for primary key and relationship handling.

</details>

  </td>
  <td><a href="https://github.com/liam-hq/liam/pull/1255/files#diff-52b9ab11a0672d7499bd2071f94edbead07d3439f608ceb3ec2ae13a7acb1f67">+277/-22</a></td>

</tr>

<tr>
  <td>
    <details>
      <summary><strong>factories.ts</strong><dd><code>Added override support for relationships in factories</code>&nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

frontend/packages/db-structure/src/schema/factories.ts

<li>Updated <code>aDBStructure</code> to support overriding relationships and table <br>groups.

</details>

  </td>
  <td><a href="https://github.com/liam-hq/liam/pull/1255/files#diff-640f551b34c718670766e3442bf877abff5d08a0477e0d3f41f7ae6e1164c1a0">+2/-2</a>&nbsp; &nbsp; &nbsp; </td>

</tr>
</table></td></tr></tr></tbody></table>

## Additional Notes

___

> <details> <summary>  Need help?</summary><li>Type <code>/help how to ...</code> in the comments thread for any questions about Qodo Merge usage.</li><li>Check out the <a href="https://qodo-merge-docs.qodo.ai/usage-guide/">documentation</a> for more information.</li></details>

### CODE REVIEW

**Comment by prakha** [comment]
Screenshot 2025-04-09 at 10 12 54 AM

@MH4GF columnType and columnName are added and visible in the UI

File: frontend/packages/db-structure/src/parser/prisma/index.test.ts [hunk 1]
```diff
@@ -477,5 +477,126 @@ describe(_processor, () => {
...
+                name: '_CategoryToPost_AB_pkey',
+                columns: ['A', 'B'],
+                unique: true,
+              }),
+              _CategoryToPost_B_index: anIndex({
+                name: '_CategoryToPost_B_index',
+                columns: ['B'],
+                unique: false,
+              }),
+            },
```
Comment (MH4GF) [inline frontend/packages/db-structure/src/parser/prisma/index.test.ts:572]: Nice 👍🏻 
ref: https://www.prisma.io/docs/orm/prisma-schema/data-model/relations/many-to-many-relations#indexes

**Review by MH4GF — APPROVED** [review]
LGTM 👍🏻 Thanks for your patience!
@prakha Please add changeset?

**Comment by MH4GF** [comment]
@prakha I created changeset, I'll merge now!

**Comment by MH4GF** [comment]
@prakha It's like CI is failed due to the latest main changes. Could you please check?

**Comment by prakha** [comment]
@MH4GF i am travelling today, not free today.

**Comment by MH4GF** [comment]
@prakha OK ✈️

**Comment by prakha** [comment]
@MH4GF i have update the branch also, but still the error is coming.

**Comment by MH4GF** [comment]
@prakha Please import this PR: https://github.com/liam-hq/liam/pull/1168

File: frontend/packages/db-structure/src/parser/prisma/parser.ts [hunk 2]
```diff
@@ -232,4 +312,179 @@ function normalizeConstraintName(
...
+ * Creates a join table for a many-to-many relationship
+ */
+function createManyToManyJoinTable(
+  joinTableName: string,
+  table_A_ColumnType: string,
+  table_B_ColumnType: string,
+): Table {
+  return {
+    name: joinTableName,
+    columns: {
```
Comment (hoshinotsuyoshi) [inline frontend/packages/db-structure/src/parser/prisma/parser.ts:332]: I checked on commit 96bf85088d10de3dfd242e3bd4800ad4721f2c05 
Running `$ pnpm --filter @liam-hq/db-structure lint` results in the following error:


```
[tsc] src/parser/prisma/parser.ts(330,3): error TS2741: Property 'constraints' is missing in type '{ name: string; columns: { A: { name: string; type: string; default: null; notNull: true; unique: false; primary: false; comment: null; check: null; }; B: { name: string; type: string; default: null; notNull: true; unique: false; primary: false; comment: null; check: null; }; }; comment: null; indexes: { ...; }; }' but required in type '{ name: string; columns: { [x: string]: { name: string; type: string; default: string | number | boolean | null; check: string | null; primary: boolean; unique: boolean; notNull: boolean; comment: string | null; }; }; comment: string | null; indexes: { ...; }; constraints: { ...; }; }'.
```

It seems like the `constraints` field is now required?

Possibly fixed with something like:

```diff
--- a/frontend/packages/db-structure/src/parser/prisma/parser.ts
+++ b/frontend/packages/db-structure/src/parser/prisma/parser.ts
@@ -329,6 +329,7 @@ function createManyToManyJoinTable(
 ): Table {
   return {
     name: joinTableName,
+    constraints: {},
     columns: {
       A: {
         name: 'A',
```

File: frontend/packages/db-structure/src/parser/prisma/index.test.ts [hunk 3]
```diff
@@ -477,5 +477,126 @@ describe(_processor, () => {
...
+          categories Category[]
+        }
+        model Category {
+          id    Int    @id @default(autoincrement())
+          name  String
+          posts Post[]
+        }
+      `)
+
+      const expectedDBStructure = aDBStructure({
```
Comment (hoshinotsuyoshi) [inline frontend/packages/db-structure/src/parser/prisma/index.test.ts:495]: I checked on commit https://github.com/liam-hq/liam/commit/96bf85088d10de3dfd242e3bd4800ad4721f2c05

Running $ pnpm --filter @liam-hq/db-structure lint results in the following error:

```
[tsc] src/parser/prisma/index.test.ts(495,35): error TS2304: Cannot find name 'aDBStructure'.
```


This appears to be caused by the changes introduced in https://github.com/liam-hq/liam/pull/1347 🙇
It might be fixed with a change like this:

```diff
--- a/frontend/packages/db-structure/src/parser/prisma/index.test.ts
+++ b/frontend/packages/db-structure/src/parser/prisma/index.test.ts
@@ -492,7 +492,7 @@ describe(_processor, () => {
         }
       `)

-      const expectedDBStructure = aDBStructure({
+      const expectedSchema = aSchema({
         tables: {
           Post: aTable({
             name: 'Post',
@@ -596,7 +596,7 @@ describe(_processor, () => {
         },
       })

-      expect(value).toEqual(expectedDBStructure)
+      expect(value).toEqual(expectedSchema)
     })
   })
 })


```

**Comment by prakha** [comment]
@MH4GF i have solved the issue.

**Review by MH4GF — APPROVED** [review]
Wonderful!!!
